name: Update Mahsa Core

on:
  workflow_dispatch:
 
jobs:
  update-core:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Latest Mahsa Core Release
        run: |
          LATEST_RELEASE_URL=$(curl -s https://api.github.com/repos/GFW-knocker/AndroidLibXrayLite/releases/latest | grep "browser_download_url.*libv2ray.aar" | cut -d '"' -f 4)
          CORE_VERSION=$(curl -s https://api.github.com/repos/GFW-knocker/AndroidLibXrayLite/releases/latest | grep '"tag_name":' | cut -d '"' -f 4)

          if [ -n "$LATEST_RELEASE_URL" ]; then
              echo "Downloading libv2ray.aar from $LATEST_RELEASE_URL"
              curl -L -o libv2ray.aar "$LATEST_RELEASE_URL"
              echo "Download completed: libv2ray.aar"
              echo "Core Version: $CORE_VERSION"
          else
              echo "Failed to find the libv2ray.aar file."
          fi

      - name: move libv2ray.aar to Mahsa Core
        run: |
          mkdir -p android/libs
          mv libv2ray.aar ./android/libs/libv2ray.aar

      - name: Update Mahsa Core
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update Mahsa Core to version $CORE_VERSION" && git push)
